# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 是玩客亦是顽壳
name: onekook
email: onekook.me@gmail.com
location: Shanghai, China
company: ONEKOOK
company_url: https://onekook.com
github_url: https://github.com/kookone
github_username: kookone
description: 是玩客亦是顽壳
favicon: favicon.png # Image must be in assets/images
repository: kookone/kookone.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url.
url: http://kookone.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disqus
disqus:
  username: onekook

enable_comments: true

comments_provider: gitalk

gitment:
  owner: kookone
  repo: blog-comments
  oauth:
    client_id: 328d2373a8e2964246c3
    client_secret: 5c5669bf128e10ecca80498b1b263273187faa68

gitalk:
  owner: kookone
  repo: blog-comments
  clientID: 328d2373a8e2964246c3
  clientSecret: 5c5669bf128e10ecca80498b1b263273187faa68
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus: true

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /Spring-Cloud
    label: Spring-Cloud

  -
    href: /Kubernetes
    label: Kubernetes

  -
    href: /blog
    label: Blog

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C#, PHP, MySQL, MongoDB, Oracle, Redis, SQLite, PL/SQL, Design Patterns, CI/CD]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, Spring Cloud, Docker, Kubernetes]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, iOS, Sketch UI Desgin]
